-- MySQL Script generated by MySQL Workbench
-- Thu Aug 20 17:54:44 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sar
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sar
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sar` DEFAULT CHARACTER SET utf8 ;
USE `sar` ;

-- -----------------------------------------------------
-- Table `sar`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sar`.`Produto` (
  `idProduto` INT NOT NULL,
  `NomeProduto` VARCHAR(45) NULL,
  `Unidade` VARCHAR(45) NULL,
  `EstoqueMax` INT NULL,
  `EstoqueMin` INT NULL,
  PRIMARY KEY (`idProduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sar`.`Estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sar`.`Estoque` (
  `idEstoque` INT NOT NULL,
  PRIMARY KEY (`idEstoque`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sar`.`Cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sar`.`Cargo` (
  `idCargo` INT NOT NULL,
  `NomeCargo` VARCHAR(45) NULL,
  PRIMARY KEY (`idCargo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sar`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sar`.`Funcionario` (
  `idFuncionario` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Salario` FLOAT NULL,
  `Logradouro` VARCHAR(45) NULL,
  `Numero` INT NULL,
  `Bairro` VARCHAR(45) NULL,
  `Cidade` VARCHAR(45) NULL,
  `Estado` VARCHAR(45) NULL,
  `Telefone` VARCHAR(45) NULL,
  `Cargo_idCargo` INT NOT NULL,
  PRIMARY KEY (`idFuncionario`, `Cargo_idCargo`),
  INDEX `fk_Funcionario_Cargo1_idx` (`Cargo_idCargo` ASC),
  CONSTRAINT `fk_Funcionario_Cargo1`
    FOREIGN KEY (`Cargo_idCargo`)
    REFERENCES `sar`.`Cargo` (`idCargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sar`.`Venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sar`.`Venda` (
  `idVenda` INT NOT NULL,
  `DataVenda` DATE NULL,
  `Estoque_idEstoque` INT NOT NULL,
  `Funcionario_idFuncionario` INT NOT NULL,
  PRIMARY KEY (`idVenda`, `Estoque_idEstoque`, `Funcionario_idFuncionario`),
  INDEX `fk_Venda_Estoque1_idx` (`Estoque_idEstoque` ASC),
  INDEX `fk_Venda_Funcionario1_idx` (`Funcionario_idFuncionario` ASC),
  CONSTRAINT `fk_Venda_Estoque1`
    FOREIGN KEY (`Estoque_idEstoque`)
    REFERENCES `sar`.`Estoque` (`idEstoque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venda_Funcionario1`
    FOREIGN KEY (`Funcionario_idFuncionario`)
    REFERENCES `sar`.`Funcionario` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sar`.`Cardapio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sar`.`Cardapio` (
  `idCardapio` INT NOT NULL,
  `NomeCardapio` VARCHAR(45) NULL,
  `Preço` INT NULL,
  `Venda_idVenda` INT NOT NULL,
  PRIMARY KEY (`idCardapio`, `Venda_idVenda`),
  INDEX `fk_Cardapio_Venda1_idx` (`Venda_idVenda` ASC),
  CONSTRAINT `fk_Cardapio_Venda1`
    FOREIGN KEY (`Venda_idVenda`)
    REFERENCES `sar`.`Venda` (`idVenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sar`.`Item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sar`.`Item` (
  `Produto_idProduto` INT NOT NULL,
  `Cardapio_idCardapio` INT NOT NULL,
  `Quantidade` INT NULL,
  `Unidade` VARCHAR(45) NULL,
  PRIMARY KEY (`Produto_idProduto`, `Cardapio_idCardapio`),
  INDEX `fk_Produto_has_Cardapio_Cardapio1_idx` (`Cardapio_idCardapio` ASC),
  INDEX `fk_Produto_has_Cardapio_Produto_idx` (`Produto_idProduto` ASC),
  CONSTRAINT `fk_Produto_has_Cardapio_Produto`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `sar`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_has_Cardapio_Cardapio1`
    FOREIGN KEY (`Cardapio_idCardapio`)
    REFERENCES `sar`.`Cardapio` (`idCardapio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sar`.`Compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sar`.`Compra` (
  `idCompra` INT NOT NULL,
  `DataCompra` DATE NULL,
  `Estoque_idEstoque` INT NOT NULL,
  PRIMARY KEY (`idCompra`, `Estoque_idEstoque`),
  INDEX `fk_Compra_Estoque1_idx` (`Estoque_idEstoque` ASC),
  CONSTRAINT `fk_Compra_Estoque1`
    FOREIGN KEY (`Estoque_idEstoque`)
    REFERENCES `sar`.`Estoque` (`idEstoque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sar`.`ItemCompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sar`.`ItemCompra` (
  `Compra_idCompra` INT NOT NULL,
  `Produto_idProduto` INT NOT NULL,
  `Preço` INT NULL,
  `Quantidade` INT NULL,
  `Validade` DATE NULL,
  PRIMARY KEY (`Compra_idCompra`, `Produto_idProduto`),
  INDEX `fk_Compra_has_Produto_Produto1_idx` (`Produto_idProduto` ASC),
  INDEX `fk_Compra_has_Produto_Compra1_idx` (`Compra_idCompra` ASC),
  CONSTRAINT `fk_Compra_has_Produto_Compra1`
    FOREIGN KEY (`Compra_idCompra`)
    REFERENCES `sar`.`Compra` (`idCompra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Compra_has_Produto_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `sar`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sar`.`TipoDespesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sar`.`TipoDespesa` (
  `idTipoDespesa` INT NOT NULL,
  `NomeDespesa` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipoDespesa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sar`.`Despesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sar`.`Despesa` (
  `idDespesa` INT NOT NULL,
  `ValorDespesa` FLOAT NULL,
  `ValorPago` FLOAT NULL,
  `DataVencimento` DATE NULL,
  `DataPagamento` DATE NULL,
  `Funcionario_idFuncionario` INT NOT NULL,
  `TipoDespesa_idTipoDespesa` INT NOT NULL,
  PRIMARY KEY (`idDespesa`, `Funcionario_idFuncionario`, `TipoDespesa_idTipoDespesa`),
  INDEX `fk_Despesa_Funcionario1_idx` (`Funcionario_idFuncionario` ASC),
  INDEX `fk_Despesa_TipoDespesa1_idx` (`TipoDespesa_idTipoDespesa` ASC),
  CONSTRAINT `fk_Despesa_Funcionario1`
    FOREIGN KEY (`Funcionario_idFuncionario`)
    REFERENCES `sar`.`Funcionario` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Despesa_TipoDespesa1`
    FOREIGN KEY (`TipoDespesa_idTipoDespesa`)
    REFERENCES `sar`.`TipoDespesa` (`idTipoDespesa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sar`.`Motivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sar`.`Motivo` (
  `idMotivo` INT NOT NULL,
  `NomeMotivo` VARCHAR(45) NULL,
  PRIMARY KEY (`idMotivo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sar`.`Saida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sar`.`Saida` (
  `idSaida` INT NOT NULL,
  `Quantia` FLOAT NULL,
  `DataSaida` DATE NULL,
  `Saidacol` VARCHAR(45) NULL,
  `Funcionario_idFuncionario` INT NOT NULL,
  `Funcionario_Cargo_idCargo` INT NOT NULL,
  `Motivo_idMotivo` INT NOT NULL,
  PRIMARY KEY (`idSaida`, `Funcionario_idFuncionario`, `Funcionario_Cargo_idCargo`, `Motivo_idMotivo`),
  INDEX `fk_Saida_Funcionario1_idx` (`Funcionario_idFuncionario` ASC, `Funcionario_Cargo_idCargo` ASC),
  INDEX `fk_Saida_Motivo1_idx` (`Motivo_idMotivo` ASC),
  CONSTRAINT `fk_Saida_Funcionario1`
    FOREIGN KEY (`Funcionario_idFuncionario` , `Funcionario_Cargo_idCargo`)
    REFERENCES `sar`.`Funcionario` (`idFuncionario` , `Cargo_idCargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Saida_Motivo1`
    FOREIGN KEY (`Motivo_idMotivo`)
    REFERENCES `sar`.`Motivo` (`idMotivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
